# In your Dockerfile.
FROM node:10.8.0

# The base node image sets a very verbose log level.
ENV NPM_CONFIG_LOGLEVEL warn

RUN npm install -g serve
CMD serve -s build
EXPOSE 5000

COPY package.json package.json
RUN npm install

COPY . .

RUN npm run build --production
